name: Format Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Run Prettier
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: ${{ github.event_name == 'pull_request' && '--check .' || '--write .' }}
          commit_message: "gh-actions: format code"
          github_token: ${{ secrets.GITHUB_TOKEN }}
